### PR TITLE
fix: Kink attributes and languages now highlight correctly

### LINKED ISSUE #105: Highlight matching language tag

### PR DESCRIPTION
**Pull request by matortheeternal**
Another improvement to tag highlighting, this time focusing on NSFW kink-related tags.  Before you would see tags highlighted if you had both selected the same kink, but what people really want to know is when a giving/receiving kink matches up - e.g. Brat and Brat Tamer, or Rope Bunny and Rigger.

We had this in the data already via the metadata property, we just weren't using it.  This PR adjusts the `AttributeList` component to use the pair metadata value when the attribute type being checked is `kink`.

EDIT: Also decided to fix #105.

### CODE REVIEW

**Comment by matortheeternal** [comment]
Also figured I could fix #105 at the same time.

**Comment by matortheeternal** [comment]
Right now this is just a bandage kind of fix, it's not ideal.  I think if we wanted to make this implementation better we could provide a `Matcher` to the AttributeList component which would comply to an interface and allow us to use a specific matcher for each `AttributeList`.

**Comment by matortheeternal** [comment]
check changes prior to 278591f to see a more minimal PR.  can drop that commit if the refactor is not preferred over that simpler implementation.

File: apps/frontend/src/components/profile/pill/expansion.tsx [hunk 1]
```diff
@@ -25,6 +27,15 @@ export const PillCollectionExpansion: FC<PillCollectionExpansionProps> = (
 	const { editable, user, attributes, session } = props;
 	const [expanded, setExpanded] = useState(false);
 
+	const kinks = useAttributeList("kink");
+	const activeKinkIds = useMemo(
+		() =>
+			filterBy(session.user.profile.attributes, "type", "kink")
+				.map(({ id }) => kinks.find((kink) => kink.id === id)?.metadata.pair)
```
Comment (matortheeternal) [inline apps/frontend/src/components/profile/pill/expansion.tsx:34]: doing a find in a map is a little messy, alternatively you could `reduce` kinks into an object where keys correspond to ids and values correspond to `metadata.pair`.

```js
const kinkPairs = kinks.reduce((pairs, kink) => {
  pairs[kink.id] = kink.metadata.pair;
  return pairs;
}, {});
```

**Review by ariesclark — APPROVED** [review]
